{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import shotstack_sdk as shotstack\n",
    "import os\n",
    "import sys\n",
    "\n",
    "from shotstack_sdk.api import edit_api\n",
    "from shotstack_sdk.model.clip import Clip\n",
    "from shotstack_sdk.model.track import Track\n",
    "from shotstack_sdk.model.timeline import Timeline\n",
    "from shotstack_sdk.model.output import Output\n",
    "from shotstack_sdk.model.edit import Edit\n",
    "from shotstack_sdk.model.crop import Crop\n",
    "from shotstack_sdk.model.video_asset import VideoAsset\n",
    "from shotstack_sdk.model.rotate_transformation import RotateTransformation\n",
    "from shotstack_sdk.model.skew_transformation import SkewTransformation\n",
    "from shotstack_sdk.model.flip_transformation import FlipTransformation\n",
    "from shotstack_sdk.model.transformation import Transformation\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    host = \"https://api.shotstack.io/stage\"\n",
    "\n",
    "    configuration = shotstack.Configuration(host = host)\n",
    "\n",
    "    configuration.api_key['DeveloperKey'] = os.getenv(\"SHOTSTACK_KEY\")\n",
    "    \n",
    "    with shotstack.ApiClient(configuration) as api_client:\n",
    "        api_instance = edit_api.EditApi(api_client)\n",
    "\n",
    "        crop = Crop(\n",
    "            top   = 0.20,\n",
    "            bottom= 0.20,\n",
    "            left  = 0.20,\n",
    "            right = 0.20\n",
    "        )\n",
    "        \n",
    "        video_asset = VideoAsset(\n",
    "        src = \"https://s3-ap-southeast-2.amazonaws.com/shotstack-assets/footage/skater.hd.mp4\",\n",
    "        crop = crop\n",
    "        )\n",
    "        \n",
    "        video_clip = Clip(\n",
    "            asset = video_asset,\n",
    "            start = 0.0,\n",
    "            length= 8.0\n",
    "        )\n",
    "    \n",
    "        track = Track(clips=[video_clip])\n",
    "\n",
    "        timeline = Timeline(\n",
    "            background = \"#000000\",\n",
    "            tracks     = [track]\n",
    "        )\n",
    "\n",
    "        output = Output(\n",
    "            format      = \"mp4\",\n",
    "            resolution  = \"sd\"\n",
    "        )\n",
    "\n",
    "        edit = Edit(\n",
    "            timeline = timeline,\n",
    "            output   = output\n",
    "        )\n",
    "\n",
    "        try:\n",
    "            api_response = api_instance.post_render(edit)\n",
    "\n",
    "            message = api_response['response']['message']\n",
    "            id = api_response['response']['id']\n",
    "        \n",
    "            print(f\"{message}\\n\")\n",
    "            print(f\">> render id: {id}\")\n",
    "        except Exception as e:\n",
    "            print(f\"Unable to resolve API call: {e}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.5 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.5"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "320c2aa7335eeb14aab0f62951f10a1684c6fc87df598ed296cdfb09eda94d8c"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
